import os
from datetime import datetime

def notify(summary: dict, output_path: str = "logs/report.md") -> None:
    """
    Creates a Markdown report summarizing the agent outputs.
    
    Args:
        summary (dict): Dictionary with keys like 'drift', 'validation', 'fix_log'.
        output_path (str): Where to save the report.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open(output_path, "w") as f:
        f.write(f"# 🧠 Agentic ETL Report\n\n")
        f.write(f"**Timestamp:** {timestamp}\n\n")

        if drift := summary.get("drift"):
            f.write("## 🔍 Schema Drift Detected\n")
            for col in drift:
                f.write(f"- {col}\n")
            f.write("\n")

        if validation := summary.get("validation"):
            f.write("## ✅ Validation Results\n")
            for key, val in validation.items():
                f.write(f"- **{key}**: {val}\n")
            f.write("\n")

        if fix_log := summary.get("fix_log"):
            f.write("## 🛠 Fix Log\n")
            for key, val in fix_log.items():
                f.write(f"- **{key}**: {val}\n")
            f.write("\n")

        f.write("---\n_Report generated by Agentic ETL System_\n")
